In [2]:
import numpy as np

print(np.__version__)

1.14.3


In [3]:
np.unravel_index(10,(6,7,8))

(0, 1, 2)

In [9]:
a=np.random.random((5,5))
a_max = a.max()
a_min = a.min()
a_1 = (a-a_min)/(a_max - a_min)
print(a)

[[0.10885909 0.26471889 0.43319374 0.59994997 0.88125216]
 [0.19287028 0.89971134 0.92340884 0.53508121 0.00837392]
 [0.47255356 0.27448444 0.72441444 0.40257386 0.81012333]
 [0.83666889 0.73617436 0.6216977  0.63633845 0.54185204]
 [0.190334   0.36706203 0.1326145  0.02046071 0.13251311]]


In [11]:
b1=np.random.randint(0,10,10)
b2=np.random.randint(0,10,10)
print(b1)
print(b2)
print(np.intersect1d(b1,b2))

[2 7 1 2 4 5 3 2 8 1]
[3 5 5 3 2 4 2 8 6 8]
[2 3 4 5 8]


In [80]:
today = np.datetime64('today','D')
print(today)
yesterday = np.datetime64('today','D') - np.timedelta64(1,'D')
print(yesterday)
tomorrow = np.datetime64('today','D') + np.timedelta64(1,'D')
#type(tomorrow)
print('tomorrow is :',tomorrow )

2018-10-01
2018-09-30
tomorrow is : 2018-10-02


In [22]:
ndates = np.arange('2018-10-01','2018-10-30',dtype='datetime64[D]')
ndates

array(['2018-10-01', '2018-10-02', '2018-10-03', '2018-10-04',
       '2018-10-05', '2018-10-06', '2018-10-07', '2018-10-08',
       '2018-10-09', '2018-10-10', '2018-10-11', '2018-10-12',
       '2018-10-13', '2018-10-14', '2018-10-15', '2018-10-16',
       '2018-10-17', '2018-10-18', '2018-10-19', '2018-10-20',
       '2018-10-21', '2018-10-22', '2018-10-23', '2018-10-24',
       '2018-10-25', '2018-10-26', '2018-10-27', '2018-10-28',
       '2018-10-29'], dtype='datetime64[D]')

In [24]:
help(np.datetime64)

Help on class datetime64 in module numpy:

class datetime64(generic)
 |  Base class for numpy scalar types.
 |  
 |  Class from which most (all?) numpy scalar types are derived.  For
 |  consistency, exposes the same API as `ndarray`, despite many
 |  consequent attributes being either "get-only," or completely irrelevant.
 |  This is the class from which it is strongly suggested users should derive
 |  custom scalar types.
 |  
 |  Method resolution order:
 |      datetime64
 |      generic
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __hash__(self, /)
 |      Return hash(self).
 |  
 |  __le__(self, value, /)
 |      Return self<=value.
 |  
 |  __lt__(self, value, /)
 |      Return self<value.
 |  
 |  __ne__(self, value, /)
 |      Return self!=value.
 |  
 |  __new__(*args, **kwargs) fr

In [40]:
f1=np.random.uniform(50,10,10)
f2=np.floor(f1)
print(f1)
print(f2)


[35.5228839  48.36144836 43.82356232 21.09216897 35.99327187 46.4551691
 32.12265585 38.01345721 19.89989828 31.8412303 ]
[35. 48. 43. 21. 35. 46. 32. 38. 19. 31.]


In [43]:
c=np.zeros(5)
c[2] = 10
print(c)
c.flags.writeable=False
#c[3] = 100

[ 0.  0. 10.  0.  0.]


In [58]:
d = np.ones(15)
np.set_printoptions(threshold=15)
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [50]:
help(np.set_printoptions)

Help on function set_printoptions in module numpy.core.arrayprint:

set_printoptions(precision=None, threshold=None, edgeitems=None, linewidth=None, suppress=None, nanstr=None, infstr=None, formatter=None, sign=None, floatmode=None, **kwarg)
    Set printing options.
    
    These options determine the way floating point numbers, arrays and
    other NumPy objects are displayed.
    
    Parameters
    ----------
    precision : int or None, optional
        Number of digits of precision for floating point output (default 8).
        May be `None` if `floatmode` is not `fixed`, to print as many digits as
        necessary to uniquely specify the value.
    threshold : int, optional
        Total number of array elements which trigger summarization
        rather than full repr (default 1000).
    edgeitems : int, optional
        Number of array items in summary at beginning and end of
        each dimension (default 3).
    linewidth : int, optional
        The number of characters p

In [64]:
e1=np.arange(100)
e2=np.random.uniform(50,20)
print(e2)
e3=np.abs(e1-e2)
print(e3)
index = e3.argmin()
print(index)

30.670510925155014
[30.67051093 29.67051093 28.67051093 ... 66.32948907 67.32948907
 68.32948907]
31


In [66]:
help(np.argmin)

Help on function argmin in module numpy.core.fromnumeric:

argmin(a, axis=None, out=None)
    Returns the indices of the minimum values along an axis.
    
    Parameters
    ----------
    a : array_like
        Input array.
    axis : int, optional
        By default, the index is into the flattened array, otherwise
        along the specified axis.
    out : array, optional
        If provided, the result will be inserted into this array. It should
        be of the appropriate shape and dtype.
    
    Returns
    -------
    index_array : ndarray of ints
        Array of indices into the array. It has the same shape as `a.shape`
        with the dimension along `axis` removed.
    
    See Also
    --------
    ndarray.argmin, argmax
    amin : The minimum value along a given axis.
    unravel_index : Convert a flat index into an index tuple.
    
    Notes
    -----
    In case of multiple occurrences of the minimum values, the indices
    corresponding to the first occurrence ar

In [69]:
e1
np.unravel_index(21,e1.shape)


(21,)

In [75]:
g=np.random.randint(10,dtype=np.int32)
print(g.dtype)
g2 = g.astype(np.float32)
print(g2.dtype)

int32
float32


In [79]:
z=np.arange(9).reshape((3,3))
print(z)
for index,value in np.ndenumerate(z):
    print(index,value)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [87]:
h=np.random.randint(0,10,(3,3)) #aaaa
print(h)
print(h[h[:,0].argsort()])

[[1 9 3]
 [9 6 6]
 [1 3 3]]
[[1 9 3]
 [1 3 3]
 [9 6 6]]


In [86]:
i=np.array([2,3,2,4,1,4,9,10,8,0])
i2 = np.arange(i.min(),i.max()+1)
print(i2)
np.bincount(i)


[ 0  1  2  3  4  5  6  7  8  9 10]


array([1, 1, 2, 1, 2, 0, 0, 0, 1, 1, 1])

In [91]:
j=np.arange(25).reshape(5,5)
print(j)
print(j[0,4])
j[[2,4]] = j[[4,2]]
print(j)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
4
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [20 21 22 23 24]
 [15 16 17 18 19]
 [10 11 12 13 14]]


In [94]:
k=np.random.randint(0,10,50)
np.set_printoptions(threshold=1000)
print(k)
print(np.bincount(k).argmax())

[2 2 0 4 1 4 5 1 0 4 9 5 3 4 1 6 8 8 1 0 6 3 2 1 9 0 2 4 7 8 0 4 6 4 9 6 6
 2 7 5 4 7 5 4 1 0 2 1 2 9]
4


In [106]:
l=np.arange(100000)
np.random.shuffle(l)
#print(l)
n=7
l2=np.argpartition(-l,n)
#print(l2)
#print(l[l2])
print((l[l2])[:n])

[99995 99993 99997 99994 99998 99996 99999]
