艾拉托斯特尼筛法

In [1]:
import numpy as np

a = np.arange(1,101)
n_max = int(np.sqrt(len(a)))
is_prime = np.ones(len(a), dtype=bool)
is_prime[0] = False

for i in range(2,n_max):
    if i in a[is_prime]:
        is_prime[(i**2-1)::i] = False

print(a[is_prime])

[ 2  3  5  7 11 13 17 19 23 29 31 37 41 43 47 53 59 61 67 71 73 79 83 89
 97]


In [6]:
a[3**2-1::3]

array([ 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57,
       60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [7]:
b = np.random.randint(1,5,(6,4))
b

array([[4, 2, 2, 2],
       [1, 3, 3, 3],
       [4, 3, 4, 1],
       [1, 1, 4, 1],
       [2, 1, 1, 3],
       [2, 1, 4, 3]])

In [8]:
b.min(axis=1)

array([2, 1, 1, 1, 1, 1])

In [11]:
c=np.arange(1,31).reshape(5,6)
c

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [20]:
c.min(axis=0)

array([1, 2, 3, 4, 5, 6])