# 最小二乘法实现线性回归

In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv("boston.csv")

In [3]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
CRIM       506 non-null float64
ZN         506 non-null float64
INDUS      506 non-null float64
CHAS       506 non-null float64
NOX        506 non-null float64
RM         506 non-null float64
AGE        506 non-null float64
DIS        506 non-null float64
RAD        506 non-null float64
TAX        506 non-null float64
PTRATIO    506 non-null float64
B          506 non-null float64
LSTAT      506 non-null float64
MEDV       506 non-null float64
dtypes: float64(14)
memory usage: 55.4 KB


In [16]:
A=list(range(12))

In [17]:
A

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [19]:
B=np.asmatrix(A).reshape(3,-1)

In [20]:
B

matrix([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [21]:
B.T

matrix([[ 0,  4,  8],
        [ 1,  5,  9],
        [ 2,  6, 10],
        [ 3,  7, 11]])

In [22]:
B.I

matrix([[-0.3375    , -0.1       ,  0.1375    ],
        [-0.13333333, -0.03333333,  0.06666667],
        [ 0.07083333,  0.03333333, -0.00416667],
        [ 0.275     ,  0.1       , -0.075     ]])

In [23]:
B.ravel()

matrix([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [28]:
type(B)

numpy.matrixlib.defmatrix.matrix

In [31]:
d1= pd.DataFrame(B,columns=('A','B','C','D'))

In [32]:
d1


A  B   C   D
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [41]:
new_columns = d1.columns.insert(0,'A0')

In [48]:
d2 = d1.reindex(columns=new_columns, fill_value=1)
d2

A0  A  B   C   D
0   1  0  1   2   3
1   1  4  5   6   7
2   1  8  9  10  11

In [46]:
d2['A0'] = 0

In [49]:
d2

A0  A  B   C   D
0   1  0  1   2   3
1   1  4  5   6   7
2   1  8  9  10  11

In [50]:
A


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [51]:
C=np.asarray(A)

In [55]:
D=C.reshape(4,-1)
D

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [61]:
s=np.std(D,axis=0)

In [62]:
m=np.mean(D,axis=0)

In [63]:
D=(D-m)/s

In [64]:
D

array([[-1.34164079, -1.34164079, -1.34164079],
       [-0.4472136 , -0.4472136 , -0.4472136 ],
       [ 0.4472136 ,  0.4472136 ,  0.4472136 ],
       [ 1.34164079,  1.34164079,  1.34164079]])